// import { eUserStatus } from "../../../interfaces/user";

export const USERS_MOCK: any[] = [{
    uid: '1',
    id: 1,
    // status: eUserStatus.ACTIVE,
    name: 'Patricio Fara',
    email: 'deevpfa@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/1403241?v=4',
    phone: '5491133333333',
    phonePrefix: '54',
    address: 'Av. Corrientes 1234',
    city: 'Buenos Aires',
    state: 'Buenos Aires',
    country: 'Argentina',
    zip: '1234',
    credits: 100,
    createdAt: new Date().getTime(),
    createdBy: null,
    updatedAt: null,
    updatedBy: null,
    deletedAt: null,
    isDeleted: false
}, {
    uid: '2',
    id: 2,
    // status: eUserStatus.ACTIVE,
    name: 'Luciano Romay',
    email: 'lromay@gmail.com',
    avatar: 'https://avatars.githubusercontent.com/u/1403241?v=4',
    phone: '5491133333333',
    phonePrefix: '54',
    address: 'Av. Corrientes 1234',
    city: 'Buenos Aires',
    state: 'Buenos Aires',
    country: 'Argentina',
    zip: '1234',
    credits: 100,
    createdAt: new Date().getTime(),
    createdBy: null,
    updatedAt: null,
    updatedBy: null,
    deletedAt: null,
    isDeleted: false
}]