export enum ResponseCode {
	// General
	INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY",
	INVALID_REQUEST_PARAMS = "INVALID_REQUEST_PARAMS",
	INVALID_REQUEST_HEADERS = "INVALID_REQUEST_HEADERS",
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
	ORIGIN_NOT_FOUND = "ORIGIN_NOT_FOUND",
	NOT_FOUND = "NOT_FOUND",
	METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",
	UNAUTHORIZED = "UNAUTHORIZED",
	TOKEN_EXPIRED = "TOKEN_EXPIRED",
	SERVER_ERROR = "SERVER_ERROR",
	CONNECTION_FAILED = "CONNECTION_FAILED",
	INSERT_NOT_OK = "INSERT_NOT_OK",
	INSERT_OK = "INSERT_OK",
	UPDATE_NOT_OK = "UPDATE_NOT_OK",
	UPDATE_OK = "UPDATE_OK",
	DELETE_NOT_OK = "DELETE_NOT_OK",
	DELETE_OK = "DELETE_OK",

	// Hook
	HOOK_FAILED = "HOOK_FAILED",

	// Currencies
	CURRENCY_NOT_FOUND = "CURRENCY_NOT_FOUND",
	CURRENCIES_NOT_WORKING = "CURRENCIES_NOT_WORKING",

	// Files
	FILE_NOT_FOUND = "FILE_NOT_FOUND",
	ERROR_FILE_SIZE = "ERROR_FILE_SIZE",
	ERROR_FILE_TYPE = "ERROR_FILE_TYPE",

	// Auth
	EMAIL_OR_PASSWORD_INVALID = "EMAIL_OR_PASSWORD_INVALID",
	EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
	AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED",

	// Account
	ACCOUNT_NOT_WORKING = "ACCOUNT_NOT_WORKING",

	// User
	USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
	USER_NOT_FOUND = "USER_NOT_FOUND",
	PASSWORD_NOT_MATCH = "PASSWORD_NOT_MATCH",
	USER_NOT_WORKING = "USER_NOT_WORKING",

	// Movements
	MOVEMENTS_NOT_WORKING = "MOVEMENTS_NOT_WORKING",

	// Countries | Provinces
	COUNTRY_NOT_WORKING = "COUNTRY_NOT_WORKING",
	PROVINCE_NOT_WORKING = "COUNTRY_NOT_WORKING",

	// Providers
	PROVIDER_NOT_WORKING = "PROVIDER_NOT_WORKING",

	// Payment Methods
	PAYMENT_METHOD_NOT_WORKING = "PAYMENT_METHOD_NOT_WORKING",
	PAYMENT_METHOD_INVALID = "PAYMENT_METHOD_INVALID",

	// Receipts
	RECEIPT_NOT_FOUND = "RECEIPT_NOT_FOUND",
}

export interface iResponse {
	code: ResponseCode;
}
