export enum ResponseCode {
	// General
	INVALID_REQUEST_BODY = "INVALID_REQUEST_BODY",
	INVALID_REQUEST_PARAMS = "INVALID_REQUEST_PARAMS",
	INVALID_REQUEST_HEADERS = "INVALID_REQUEST_HEADERS",
	UNAUTHORIZED = "UNAUTHORIZED",
	TOKEN_EXPIRED = "TOKEN_EXPIRED",
	NOT_FOUND = "NOT_FOUND",
	NOT_WORKING = "NOT_WORKING",
	ORIGIN_NOT_FOUND = "ORIGIN_NOT_FOUND",
	METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",
	INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
	CONNECTION_FAILED = "CONNECTION_FAILED",
	USER_ABORT_FETCH = "The user aborted a request.",

	// Database
	INSERT_NOT_OK = "INSERT_NOT_OK",
	INSERT_OK = "INSERT_OK",
	UPDATE_NOT_OK = "UPDATE_NOT_OK",
	UPDATE_OK = "UPDATE_OK",
	DELETE_NOT_OK = "DELETE_NOT_OK",
	DELETE_OK = "DELETE_OK",

	// Email & SMS
	EMAIL_SENDED = "EMAIL_SENDED",
	EMAIL_NOT_SENT = "EMAIL_NOT_SENT",
	SMS_SENDED = "SMS_SENDED",
	SMS_NOT_SENT = "SMS_NOT_SENT",
	INVALID_TO = "INVALID_TO",
	INVALID_CODE = "INVALID_CODE",
	VALID_CODE = "VALID_CODE",

	// Hook
	HOOK_FAILED = "HOOK_FAILED",

	// Currencies
	CURRENCY_NOT_FOUND = "CURRENCY_NOT_FOUND",
	CURRENCIES_NOT_WORKING = "CURRENCIES_NOT_WORKING",

	// Files
	FILE_NOT_FOUND = "FILE_NOT_FOUND",
	ERROR_FILE_SIZE = "ERROR_FILE_SIZE",
	ERROR_FILE_TYPE = "ERROR_FILE_TYPE",

	// Auth
	AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED",
	EMAIL_OR_PASSWORD_INVALID = "EMAIL_OR_PASSWORD_INVALID",
	EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
	PHONE_ALREADY_EXISTS = "PHONE_ALREADY_EXISTS",

	// Account
	ACCOUNT_NOT_WORKING = "ACCOUNT_NOT_WORKING",
	ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND",
	ACCOUNT_TAGS_NOT_WORKING = "ACCOUNT_TAGS_NOT_WORKING",
	ACCOUNT_TAGS_NOT_FOUND = "ACCOUNT_TAGS_NOT_FOUND",
	ACCOUNT_TAG_ALREADY_EXIST = "ACCOUNT_TAG_ALREADY_EXIST",

	// User
	USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
	USER_NOT_FOUND = "USER_NOT_FOUND",
	PASSWORD_NOT_MATCH = "PASSWORD_NOT_MATCH",
	USER_NOT_WORKING = "USER_NOT_WORKING",

	// Countries | Provinces
	COUNTRY_NOT_WORKING = "COUNTRY_NOT_WORKING",
	COUNTRY_NOT_FOUND = "COUNTRY_NOT_FOUND",
	PROVINCE_NOT_WORKING = "COUNTRY_NOT_WORKING",
	PROVINCE_NOT_FOUND = "COUNTRY_NOT_FOUND",
	PARAMETER_NOT_FOUND = "PARAMETER_NOT_FOUND",

	// Providers
	PROVIDER_NOT_WORKING = "PROVIDER_NOT_WORKING",
	PROVIDER_NOT_CREATED = "PROVIDER_NOT_CREATED",
	PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND",
	PROVIDER_ALREADY_EXIST = "PROVIDER_ALREADY_EXIST",
	PROVIDER_ALREADY_USED = "PROVIDER_ALREADY_USED",

	// Proxies
	PROXY_NOT_WORKING = "PROXY_NOT_WORKING",
	PROXY_NOT_FOUND = "PROXY_NOT_FOUND",
	PROXY_NOT_CREATED = "PROXY_NOT_CREATED",

	// Services
	SERVICE_NOT_FOUND = "SERVICE_NOT_FOUND",
	SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",

	// Movements
	MOVEMENTS_NOT_WORKING = "MOVEMENTS_NOT_WORKING",
	MOVEMENTS_NOT_FOUND = "MOVEMENTS_NOT_FOUND",
	MOVEMENTS_NOT_CREATED = "MOVEMENTS_NOT_CREATED",
	MOVEMENTS_NOT_UPDATED = "MOVEMENTS_NOT_UPDATED",
	MOVEMENTS_NOT_DELETED = "MOVEMENTS_NOT_DELETED",
	BALANCE_INSUFFICIENT = "BALANCE_INSUFFICIENT",
	CREDITS_INVALID = "CREDITS_INVALID",

	// Requests
	REQUEST_NOT_WORKING = "REQUEST_NOT_WORKING",
	REQUEST_NOT_FOUND = "REQUEST_NOT_FOUND",
	REQUEST_NOT_CREATED = "REQUEST_NOT_CREATED",
	REQUEST_NOT_UPDATED = "REQUEST_NOT_UPDATED",
	REQUEST_NOT_DELETED = "REQUEST_NOT_DELETED",
	REQUEST_RESOLVED = "REQUEST_RESOLVED",
	REQUEST_FAILED = "FULLDATA_REQUEST_FAILED",
	REQUEST_SENDED = "REQUEST_SENDED",
	INVALID_REQUEST = "INVALID_REQUEST",
	INVALID_PROMPT = "INVALID_PROMPT",

	// Payment Methods
	PAYMENT_METHOD_NOT_WORKING = "PAYMENT_METHOD_NOT_WORKING",
	PAYMENT_METHOD_NOT_FOUND = "PAYMENT_METHOD_NOT_FOUND",
	PAYMENT_METHOD_INVALID = "PAYMENT_METHOD_INVALID",

	// Receipts
	RECEIPT_NOT_FOUND = "RECEIPT_NOT_FOUND",
}

export interface ResponseCommon {
	code: ResponseCode | keyof typeof ResponseCode;
}
